#!/usr/bin/env bash

command="$1"
if [ -z $command ]; then

  cat <<USAGE
'$CHPG_RELEASE' release

usage: chpg @[<version>]
       chpg -f FILE
       chpg reshim
       chpg which COMMAND
       chpg resolve
       chpg help [CMD]
       chpg status
       chpg list
       chpg init [--auto] [--quiet]
       chpg --version

More Info:
  https://github.com/redding/chpg/blob/$CHPG_RELEASE/README.md
USAGE
  exit 0

else

  if [[ "$command" == "reshim" ]]; then

    cat <<USAGE
Regenerate shims for all installed Postgres.app versions.

usage: chpg reshim
USAGE
    exit 0

  elif [[ "$command" == "which" ]]; then

    cat <<USAGE
Print the real path the given command resolves to in the current dir.

usage: chpg which COMMAND
USAGE
    exit 0

  elif [[ "$command" == "resolve" ]]; then

    cat <<USAGE
Print the Postgres version + source that applies in the current dir.

usage: chpg resolve
USAGE
    exit 0

  elif [[ "$command" == "help" ]]; then

    cat <<USAGE
Print command usage info.

usage: chpg help
       chpg help [cmd]
USAGE
    exit 0

  elif [[ "$command" == "status" ]]; then

    cat <<USAGE
Print the current version and Postgres.app path info

usage: chpg status
USAGE
    exit 0

  elif [[ "$command" == "list" ]]; then

    cat <<USAGE
List the available versions, marking the current active version

usage: chpg list
USAGE
    exit 0

  elif [[ "$command" == "init" ]]; then

    cat <<USAGE
Output an initialization script to eval in the shell.

usage: eval "\$(chpg init)"
       eval "\$(chpg init [--auto] [--quiet])"
USAGE
    exit 0

  else
    echo "chpg: no such command \`$command'" >&2
    exit 1
  fi

fi

